---
- name: Create snx dir
  ansible.builtin.file:
    state: directory
    path: /usr/share/snx
  become: true
  tags: snx

- name: Install dependencies
  ansible.builtin.package:
    state: present
    name:
      - libstdc++5:i386
      - libx11-6:i386
      - libpam0g:i386
  become: true
  tags: snx

- name: Copy snx installation script
  ansible.builtin.copy:
    src: snx_install_n.sh
    dest: '/usr/share/snx/snx_install_n.sh'
    mode: 0755
  become: true
  tags: snx

- name: Install snx
  ansible.builtin.command:
    cmd: ./snx_install_n.sh
    chdir: /usr/share/snx
    creates: /usr/bin/snx
  become: true
  tags: snx

- name: Copy snx.sh script
  ansible.builtin.template:
    src: snx_vpn.sh.j2
    dest: '{{ ansible_user_dir }}/.local/bin/snx.sh'
    owner: '{{ ansible_user_id }}'
    mode: 0755
  tags: snx
