if [ "$CURSOR_INVOKED_AS" = "cursor-agent" ]; then
  return
fi

load_file () {
  file="$1"
  if [ -f "${ZDOTDIR:-${HOME}}/${file}" ]; then
    source "${ZDOTDIR:-${HOME}}/${file}"
  fi
}

# options
setopt APPEND_HISTORY
setopt AUTO_CD
setopt AUTO_PUSHD
setopt INC_APPEND_HISTORY
setopt HIST_FIND_NO_DUPS
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt extendedhistory
setopt sharehistory
# remove older command from the history if a duplicate is to be added.
setopt HIST_IGNORE_ALL_DUPS

# magic zshell mv
autoload zmv

# use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# fix del key
bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line

# load parts
load_file .profile
load_file .zsh_aliases
load_file .zshfun
load_file .zshenv
load_file .zsh_podman
load_file .zplug/init.zsh
load_file .zplugrc
load_file .p10k.zsh

# get new binaries into PATH
zstyle ':completion:*' rehash true

# show menu entries on completion
zstyle ':completion:*' menu yes=long select

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/.local/share/google-cloud-sdk/path.zsh.inc" ]; then
  . "$HOME/.local/share/google-cloud-sdk/path.zsh.inc"
fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/.local/share/google-cloud-sdk/completion.zsh.inc" ]; then
  . "$HOME/.local/share/google-cloud-sdk/completion.zsh.inc"
fi
