---
- name: Restart v2ray
  ansible.builtin.service:
    name: v2ray
    state: restarted
  become: true
  tags: v2ray

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  tags: v2ray
