#!/bin/sh

if [ "$1" = "off" ]; then
  pkill spt
  notify-send "spt" "stopped"
  exit 0
elif [ "$1" = "pause" ]; then
  pkill -SIGUSR2 spt
  pkill -SIGUSR1 spt
fi

if pgrep -fx spt > /dev/null; then
  pkill -USR1 spt
else
  setsid -f spt >/dev/null 2>&1
fi
