---
- name: Restart shadowsocks-server
  ansible.builtin.service:
    name: "shadowsocks-libev-server@{{ shadowsocks_mode }}"
    state: restarted
  become: true

- name: Restart shadowsocks-client
  ansible.builtin.service:
    name: shadowsocks-libev-local@client
    state: restarted
  become: true
