---
- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  become: true
  tags: iptables

- name: Reload ipset tables
  command: ipset-reload.sh
  register: command_result
  failed_when: "command_result.rc != 0"
  become: true
  tags: iptables
