---
- name: Reload ipset tables
  ansible.builtin.command: iptables-ipset.sh --reload
  changed_when: false
  register: command_result
  failed_when: "command_result.rc != 0"
  become: true
  tags: always

- name: Restore iptables rules
  ansible.builtin.shell:
    iptables-restore < {{ iptables_v4_rules }}
  changed_when: false
  become: true
  tags: always
...
