---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install dmenu, dynamic menu for X
  company: RootIT
  license: ISC
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: package_facts
