---
- name: Install firefox
  ansible.builtin.package:
    state: present
    name: firefox-esr
  tags:
    - browser
    - xorg
    - x11
  become: true

- name: Copy bubblewrap firefox
  ansible.builtin.copy:
    src: firefox_bwrap
    dest: '{{ firefox_bwrap_path }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: true

- name: Update firefox-esr desktop
  ansible.builtin.template:
    src: firefox-esr.desktop
    dest: '{{ ansible_user_dir }}/.local/share/applications/firefox-esr.desktop'
    mode: '0644'
