---
- name: Install firefox
  ansible.builtin.package:
    state: present
    name: firefox-esr
  tags:
    - browser
    - xorg
    - x11
  become: true

- name: Configure passff
  ansible.builtin.file:
    state: directory
    path: '{{ ansible_user_dir }}/.mozilla/native-messaging-hosts'

- name: Configure passff
  ansible.builtin.template:
    src: native-messaging-hosts/passff.json.j2
    dest: '{{ ansible_user_dir }}/.mozilla/native-messaging-hosts/passff.json'
  tags:
    - browser
    - xorg
    - x11
    - pass
