---
- name: Install syncthing
  opkg:
    name: 'syncthing'
    update_cache: true
  tags: syncthing

- name: Enable syncthing in UCI config
  uci:
    command: set
    key: syncthing.syncthing.enabled
    value: 1
  notify:
    - Commit pending changes
    - Restart syncthing
  tags: syncthing

- name: Enable syncthing service
  service:
    name: syncthing
    enabled: true
  tags: syncthing
...
