#!/bin/sh

uid=$(id -u)
exec bwrap \
  --bind /home/"$USER"/.local/share/TelegramDesktop /home/"$USER"/.local/share/TelegramDesktop \
  --bind /home/"$USER"/Downloads /home/"$USER"/Downloads \
  --dev /dev \
  --dev-bind /dev/dri /dev/dri \
  --hostname housekeep \
  --die-with-parent \
  --new-session \
  --ro-bind /opt/Telegram /opt/Telegram \
  --ro-bind /run/user/"$uid"/pulse /run/user/"$uid"/pulse \
  --ro-bind /sys/dev/char /sys/dev/char \
  --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
  --ro-bind /usr/lib /usr/lib \
  --ro-bind /usr/lib64 /usr/lib64 \
  --ro-bind /etc/fonts /etc/fonts \
  --ro-bind /usr/share/fontconfig /usr/share/fontconfig \
  --ro-bind /usr/share/fonts /usr/share/fonts \
  --symlink usr/lib /lib \
  --symlink usr/lib64 /lib64 \
  --tmpfs /tmp \
  --unshare-uts \
  /opt/Telegram/Telegram > /dev/null 2>&1
