---
- name: Install duplicity
  ansible.builtin.package:
    state: present
    name:
      - duplicity
      - python3-pexpect
  tags: duplicity
  become: true

- name: Copy duplicity backup script
  ansible.builtin.template:
    src: duplicity_backup.sh.j2
    dest: '{{ ansible_user_dir }}/.local/bin/duplicity_backup.sh'
    mode: '0755'
  when: duplicity_targets is defined
  tags: duplicity

- name: Flush duplicity handlers
  ansible.builtin.meta: flush_handlers
  tags: duplicity

- name: Add cronjob for encrypted backup
  ansible.builtin.cron:
    name: Start encrypted backup
    job: '{{ ansible_user_dir }}/.local/bin/duplicity_backup.sh'
    user: '{{ ansible_user_id }}'
    minute: "{{ duplicity_update_min|default('20') }}"
    hour: "{{ duplicity_update_hour|default('1') }}"
    day: "{{ duplicity_update_day_of_month|default('*') }}"
    month: "{{ duplicity_update_month|default('*') }}"
    weekday: "{{ duplicity_update_day_of_week|default('*') }}"
  when: duplicity_targets is defined
  tags: duplicity
