---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install, configure thinkfan and configure thinkpad_acpi
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
