---
- when: ansible_facts['distribution_major_version'] <= "12"
  tags: xorg
  block:

    - name: Create fonts dir
      ansible.builtin.file:
        state: directory
        path: '{{ ansible_user_dir }}/.local/share/fonts'
        mode: '0755'

    - name: Copy fonts
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: '{{ ansible_user_dir }}/.local/share/fonts/{{ item.path }}'
        mode: '0644'
      with_community.general.filetree: "files/fonts"

    - name: Create fonts.dir
      ansible.builtin.shell:
        cmd: >
          /usr/sbin/update-fonts-dir '{{ ansible_user_dir }}/.local/share/fonts'
        creates: '{{ ansible_user_dir }}/.local/share/fonts/fonts.dir'

    - name: Update font cache
      ansible.builtin.shell:
        cmd: /usr/bin/fc-cache -f
        creates: '{{ ansible_user_dir }}/.local/share/fonts/.uuid'
