---
- name: Install X packages
  ansible.builtin.package:
    state: present
    name:
      - abiword
      - baobab
      - dbus-x11
      - feh
      - ffmpeg
      - flameshot
      - gimp
      - gnome-icon-theme
      - gnome-keyring
      - gnome-themes-extra-data
      - gsfonts-x11
      - gtk-chtheme
      - imagemagick
      - inotify-tools
      - libpam-gnome-keyring
      - libreoffice-calc
      - libreoffice-impress
      - libreoffice-writer
      - pcmanfm
      - pinentry-gnome3
      - rxvt-unicode
      - ssh-askpass-fullscreen
      - unclutter
      - unclutter-startup
      - x11-utils
      - x11-xkb-utils
      - x11-xserver-utils
      - xautolock
      - xclip
      - xdotool
      - xfonts-terminus
      - xinit
      - xinput
      - xserver-xorg
      - xserver-xorg-input-all
      - xserver-xorg-legacy
      - xserver-xorg-video-fbdev
      - xserver-xorg-video-intel
      - xserver-xorg-video-vesa
      - zathura
  tags: xorg
  become: true

- name: Install slim
  ansible.builtin.include_tasks: slim.yml
  tags: slim

- name: Copy keyboard defaults
  template:
    src: etc_default_keyboard.j2
    dest: /etc/default/keyboard
    mode: 0644
  tags: [xorg, keyboard]
  become: true

- name: Copy session scripts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ ansible_user_dir }}/.{{ item }}'
    mode: 0644
  loop:
    - gtkrc-2.0
    - xsession
    - xsessionrc
    - Xresources
  tags:
    - xorg
    - script

- name: Install fonts
  ansible.builtin.include_tasks: fonts.yml
