---
- name: Install X packages
  ansible.builtin.package:
    state: present
    name:
      - adwaita-icon-theme
      - baobab
      - dbus-x11
      - faba-icon-theme
      - feh
      - ffmpeg
      - fonts-font-awesome
      - fonts-powerline
      - fonts-takao
      - gimp
      - gnome-icon-theme
      - gnome-themes-extra-data
      - gsfonts-x11
      - imagemagick
      - inotify-tools
      - libpam-gnome-keyring
      - pcmanfm
      - pinentry-gnome3
      - rtkit
      - rxvt-unicode
      - unclutter
      - unclutter-startup
      - x11-utils
      - x11-xkb-utils
      - x11-xserver-utils
      - xautolock
      - xclip
      - xdo
      - xdotool
      - xfonts-terminus
      - xinit
      - xinput
      - xserver-xorg
      - xserver-xorg-input-all
      - xserver-xorg-legacy
      - xserver-xorg-video-fbdev
      - xserver-xorg-video-intel
      - xserver-xorg-video-vesa
      - zathura
  tags: xorg
  become: true

- name: Install urxvt
  ansible.builtin.include_tasks: urxvt.yml
  tags:
    - urxvt
    - xorg

- name: Install slim
  ansible.builtin.include_tasks: slim.yml
  tags:
    - slim
    - xorg

- name: Include fonts tasks
  ansible.builtin.include_tasks: fonts.yml
  tags:
    - fonts
    - xorg

- name: Copy keyboard defaults
  ansible.builtin.template:
    src: etc_default_keyboard.j2
    dest: /etc/default/keyboard
    mode: "0644"
  tags:
    - xorg
    - keyboard
  become: true

- name: Copy session scripts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ ansible_user_dir }}/.{{ item }}'
    mode: "0644"
  loop:
    - gtkrc-2.0
    - xsession
    - xsessionrc
    - Xresources
  tags:
    - xorg
    - script
