---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  become: true
  tags:
    - apt
    - unattended

- name: Disable service unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: stopped
    enabled: false
  become: true
  tags:
    - apt
    - unattended

- name: Create Apt auto-upgrades & unattended-upgrades configuration
  ansible.builtin.template:
    src: "50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  tags:
    - apt
    - unattended

- name: Create cronfile
  ansible.builtin.cron:
    name: unattended-upgrades
    minute: "0"
    hour: "19"
    day: "*"
    month: "*"
    weekday: "*"
    cron_file: "/etc/cron.d/unattended-upgrades"
    job: "/usr/bin/unattended-upgrade"
    user: "root"
  become: true
  tags:
    - apt
    - unattended
    - cron

- name: Create cronfile at reboot
  ansible.builtin.cron:
    name: "unattended-upgrades at reboot"
    special_time: reboot
    cron_file: "/etc/cron.d/unattended-upgrades"
    job: "/usr/bin/unattended-upgrade"
    user: "root"
  become: true
  tags:
    - apt
    - unattended
    - cron
