---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  become: true
  tags:
    - apt
    - unattended

#- name: "Create Apt auto-upgrades & unattended-upgrades configuration"
#  ansible.builtin.template:
#    src: "unattended-upgrades.j2"
#    dest: "/etc/apt/apt.conf.d/90-ansible-unattended-upgrades"
#    owner: "root"
#    group: "root"
#    mode: "0644"
