---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  become: true
  tags:
    - apt
    - unattended

- name: Enable service unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true
  become: true
  tags:
    - apt
    - unattended

- name: Create Apt auto-upgrades & unattended-upgrades configuration
  ansible.builtin.template:
    src: "50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart unattended-upgrades
  become: true
  tags:
    - apt
    - unattended
