---
galaxy_info:
  author: Stanislav Korolev
  description: Install and configure nginx with ssl support
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
