---
- name: Unarchive a telegram archive
  become: true
  ansible.builtin.unarchive:
    src: '{{ telegram_url }}'
    dest: /opt
    remote_src: yes
    owner: root
    group: root
    creates: /opt/Telegram/Telegram
  become: yes

- name: Make link
  become: true
  copy:
    src: telegram
    mode: 0755
    dest: "/usr/local/bin/telegram"
  become: yes
