#!/bin/sh

critical=8
lowlevel=20

[ "$(acpi -a | awk '{print $3}')" = "on-line" ] && exit 0

send_alert() {
    title="$1"
    body="$2"
    user="$3"
    sudo -u "$user" sh -s <<EOF
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$user")/bus \
        notify-send --urgency=critical "$title" "$body"
EOF
}

notify() {
    title="$1"
    body="$2"
    users=$(who | awk '!x[$1]++ {print $1}')
    for user in ${users}; do
        send_alert "$title" "$body" "$user"
    done
}

charge=$(acpi | awk -F',' '{printf"%d\n",$2}')

if [ "$charge" -le "$critical" ]; then
    notify "Halt system" \
        "Will now halt, battery charge critical: $charge"
    /sbin/halt -p
elif [ "$charge" -le "$lowlevel" ]; then
    notify "Attention: Low battery charge!" \
        "Battery charge: $charge"
fi
