---
- name: Update local zone from hosts
  ansible.builtin.command: build-unbound-localzone-from-hosts.pl
  register: _local_zone_update
  become: true

- name: Reload unbound
  ansible.builtin.service:
    name: unbound
    state: reloaded
  when: _local_zone_update.changed
  become: true
