#!/bin/sh

run_rtmp_stream() {
  pacmd load-module module-null-sink sink_name=RTP
  pacmd update-sink-proplist RTP device.description=RTP
  pacmd load-module module-rtp-send \
    source=RTP.monitor \
    destination_ip=224.0.0.56 \
    port=46416
}

listen_rtmp() {
  pacmd load-module module-rtp-recv
}

off() {
  pacmd unload-module module-rtp-send
  pacmd unload-module module-null-sink
  pacmd unload-module module-rtp-recv
}

case $1 in
  listen) listen_rtmp ;;
  off) off ;;
  *) run_rtmp_stream ;;
esac
