#!/bin/sh

set -e
VIDEO_HOME="${HOME}/Videos"
MPV_HISTORY="${HOME}/.config/mpv/mpvhistory.log"

dmenu_local () {
    dmenu -c -i \
        -bw 1 \
        -p video \
        -l 20
}

local_videos () {
    pattern='.*(avi|mp4|mkv|webm|m4v|m3u)$'
    find -L "$VIDEO_HOME" \
        -type f \
        -regextype posix-extended \
        -regex "$pattern" \
        -printf "%f\n"
}

history_videos() {
    awk -F'"' '{print $4}' "$MPV_HISTORY" | uniq | tac
}

linenum_by_name() {
    grep $2 -F -n "$1" "$MPV_HISTORY" | cut -f1 -d:
}

history_search() {
    # return path or url from mpv history log
    read -r name
    line_num=$(linenum_by_name "$name" -m1)
    awk -v linenum="$line_num" -F'"' 'NR == linenum {print $2}' "$MPV_HISTORY"
}

choose_file() {
    sed '/^$/d' \
        | dmenu_local
}

full_path() {
    read -r file
    find -L "$VIDEO_HOME" \
        -regextype posix-extended \
        -name "$file" \
        -printf "${VIDEO_HOME}/%P\n"
}

start_video() {
    file="$*"
    [ -z "$file" ] && read -r file
    playerctl pause
    if echo "$file" | grep -q youtube; then
        proxy=proxychains
    fi
    setsid -f $proxy mpv "$file" >/dev/null 2>&1
}

choose_target() {
    printf '%s\n' 'history' 'local' 'delete history' \
        | dmenu_local
}

del_history() {
    read -r name
    sed_lines=$(linenum_by_name "$name"| sed ':a;N;$!ba;s/\n/d;/g')
    sed -i "${sed_lines}d" "$MPV_HISTORY"
}

del_history_loop() {
    target=$(history_videos | choose_file)
    until [ -z "$target" ]; do
        echo "$target" | del_history
        target=$(history_videos | choose_file)
    done
}

run_target() {
    target=$(choose_target)
    case $target in
        local) local_videos | choose_file | full_path | start_video ;;
        history) history_videos | choose_file | history_search | start_video ;;
        "delete history") del_history_loop;;
    esac
}

if [ -n "$1" ]; then
    start_video "$1"
else
    run_target
fi
