#!/bin/sh
version=$(rpm -q --qf '%{version}' system-release)
cat << EOF

 _____               _ _                   _               
/__   \\_ __ __ _  __| (_)_ __   __ ___   _(_) _____      __
  / /\\/ '__/ _\` |/ _\` | | '_ \\ / _\` \\ \\ / / |/ _ \\ \\ /\\ / /
 / /  | | | (_| | (_| | | | | | (_| |\\ V /| |  __/\\ V  V / 
 \\/   |_|  \\__,_|\\__,_|_|_| |_|\\__, | \\_/ |_|\\___| \\_/\\_/  
                               |___/                       

https://aws.amazon.com/amazon-linux-ami/$version-release-notes/
EOF
