#!/bin/sh

cat << EOF

                      .,;:ccccc:;'.                   
                   .:llllllllllllllc,.                
                 .:lllllllllllllllllll;'..            
                'llllllllllllllllllllllllll:'.        
               .lllll;...;lllllllllllllllllllc.       
           ..',;llll:     ,lllllllllllllllll;         
        .,clllllll:.      .:llllllllllllll;.    '     
       ;llllllll;.  .,:::'  .cllllllllll;.   .;ll'    
      ,lllllll;.  .:llllllc.  ,lllllll;.   .:lllllc,  
      :llllc,. .,cllllllllll;. .;lll:.   ':llllllllll'
      :ll:' .,clllllllllllllll;. ...  .,cllllllllllll:
      .:. .;lllllllllllllllllll:     .lllllllllllllll:
        .cllllllllllllllllllllll.   .;llllllllllllllc.
         ..;:ccccccccccccccccccccc::ccccccccccccc:;.  

  _____              _ _                   _
 |_   _| __ __ _  __| (_)_ __   __ ___   _(_) _____      __
   | || '__/ _\` |/ _\` | | '_ \ / _\` \ \ / / |/ _ \ \ /\ / /
   | || | | (_| | (_| | | | | | (_| |\ V /| |  __/\ V  V /
   |_||_|  \__,_|\__,_|_|_| |_|\__, | \_/ |_|\___| \_/\_/
                               |___/

EOF
