#!/bin/sh

set -e

# home of newsboat database
DATABASE="${HOME}/.local/share/newsboat/cache.db"
# select only youtube urls from newsboat db
YOUTUBE_FILTER='url regexp ".*youtube.*"'

# shellcheck disable=SC2028
print_usage() {
  echo "$(basename "$0") view all youtube videos from newsboat youtube rss feeds\n"\
    "\nUSAGE: $(basename "$0") [OPTIONS]\n"\
    "\nOPTIONS:\n" \
    "    -h,         show this help message and exit\n"\
    "    -a AUTHOR,  filter by author\n"
  exit 0
}

get_urls() {
  author="$1"
  query="select url from rss_item where unread=1 and ${YOUTUBE_FILTER}"
  if [ -n "$author" ]; then
      query="$query and author='$author'"
  fi
  sqlite3 "$DATABASE" "$query"
}

mark_video_read() {
  url="$1"
  UPDATEQUERY="update rss_item set unread=0 where unread=1 and url='$url';"
  sqlite3 "$DATABASE" "$UPDATEQUERY"
}

select_author() {
  sqlite3 /home/daysun/.local/share/newsboat/cache.db \
    'select title from rss_feed where url REGEXP ".*youtube.*";' | \
    dmenu -bw 1 -p authors -l 10
}

while getopts 'a|h' flag; do
  case "${flag}" in
  h) print_usage ;;
  a) AUTHOR="$2" && [ -z "$AUTHOR" ] && AUTHOR=$(select_author) ;;
  *) exit 0 ;;
  esac
done

all_unreads=$(get_urls "$AUTHOR")
[ -z "$all_unreads" ] && (echo nothing found && exit 1)

for url in $all_unreads; do
  echo "Playing $url"
  proxychains mpv "$url" >/dev/null 2>&1
  echo "Mark $url as read"
  mark_video_read "$url"
done
