#!/bin/sh

set -e

URL="$1"
[ -z "$URL" ] && exit 0

YOUTUBE_URL='^https://www.youtube.com'

check_url() {
  if ! echo "$1" | grep -Eq "$2"; then
    return 1
  fi
}

run_librewolf() {
  exec setsid -f librewolf "$URL" >/dev/null 2>&1
}

run_mpv() {
  export http_proxy="http://127.0.0.1:1081"
  export https_proxy="http://127.0.0.1:1081"
  setsid -f mpv --load-select=yes --really-quiet --no-terminal -- "$1" > /dev/null 2>&1
}

if check_url "$URL" "$YOUTUBE_URL"; then
  run_mpv "$URL"
elif check_url "$URL" "\.(png|jpeg)"; then
  exec setsid -f feh "$URL"
else
  run_librewolf "$URL"
fi
