---
- name: Install desktop packages
  ansible.builtin.package:
    state: present
    name:
      - bluetooth
      - bluez
  become: true
  tags: bluetooth

- name: Copy mpris-proxy service file
  ansible.builtin.copy:
    src: mpris-proxy.service
    dest: /usr/lib/systemd/user/mpris-proxy.service
    mode: '0644'
  notify: Systemctl daemon-reload
  become: true
  tags: bluetooth

- name: Flush handlers for mpris-proxy
  ansible.builtin.meta: flush_handlers
  tags: bluetooth

- name: Enable and start mpris-proxy
  ansible.builtin.systemd:
    name: mpris-proxy
    state: started
    enabled: true
    scope: user
  tags: bluetooth

- name: Create icon and desktopfiles directory
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    recurse: true
  with_items:
    - "{{ ansible_user_dir +
      '/.local/share/applications' }}"
    - "{{ ansible_user_dir +
      '/.local/share/icons/hicolor/scalable/apps' }}"
  tags: bluetooth

- name: Copy desktopfile
  ansible.builtin.copy:
    src: 'bluetoothctl.desktop'
    dest: "{{ ansible_user_dir +
      '/.local/share/applications/bluetoothctl.desktop' }}"
    mode: '0644'
  tags: bluetooth

- name: Copy svg icon
  ansible.builtin.copy:
    src: 'bluetooth.svg'
    dest: "{{ ansible_user_dir +
      '/.local/share/icons/hicolor/scalable/apps/bluetooth.svg' }}"
    mode: '0644'
  tags: bluetooth
