---

- name: Copy modules
  file:
    state: directory
    path: /usr/local/lib/site_ruby

- name: Copy modules
  copy:
    src: ipset.rb
    dest: /usr/local/lib/site_ruby/ipset.rb

- name: Create cronfile
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.update_min|default('0') }}"
    hour: "{{ item.update_hour|default('2') }}"
    day: "{{ item.update_day_of_month|default('*') }}"
    month: "{{ item.update_month|default('*') }}"
    weekday: "{{ item.update_day_of_week|default('*') }}"
    cron_file: "/etc/cron.d/{{ item.name }}"
    job: "/usr/bin/ruby /usr/local/bin/{{ item.name }}.rb --service={{ item.service }} >> /var/log/{{ item.name }}.log 2>&1"
    user: "root"
  with_items: "{{ external_healthcheck }}"

- name: Create reboot cronfile
  cron:
    name: "{{ item.name }} after reboot"
    cron_file: "/etc/cron.d/{{ item.name }}_reboot"
    job: "sleep 300; /usr/local/bin/{{ item.name }}.rb --service={{ item.service }} >> /var/log/{{ item.name }}.log 2>&1"
    special_time: reboot
    user: "root"
  with_items: "{{ external_healthcheck }}"

- name: Copy iptables_configure_scripts
  copy:
    src: "{{ item.name }}.rb"
    dest: /usr/local/bin
    mode: u+x
  notify: Fill up ipsets
  with_items: "{{ external_healthcheck }}"
  when: external_healthcheck is defined
