---
- name: Install iptables
  ansible.builtin.package:
    name:
      - ipset
      - iptables-persistent
    cache_valid_time: 600
  become: true
  tags: iptables

- name: Copy ipset reload script
  ansible.builtin.copy:
    src: ipset-reload.sh
    dest: "/usr/bin/ipset-reload.sh"
    mode: "0755"
  become: true
  tags: iptables

- name: Iptables rules
  notify: Save iptables rules
  become: true
  tags: iptables
  block:
    - name: Set the policy for the INPUT chain to DROP
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP

    - name: Allow any traffic on lo
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow echo replies
      ansible.builtin.iptables:
        chain: INPUT
        protocol: icmp
        icmp_type: '{{ item }}'
        jump: ACCEPT
      loop: [0, 8]

    - name: Allow related and established connections
      ansible.builtin.iptables:
        action: insert
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

- name: Flush iptables handlers
  meta: flush_handlers
  tags: iptables
