---
# @var byedpi_bin_path:description: путь к исполняемому файлу byedpi
byedpi_bin_path: "/usr/local/bin/byedpi"

# @var byedpi_user:description: пользователь для запуска сервиса
byedpi_user: "byedpi"

# @var byedpi_group:description: группа для запуска сервиса
byedpi_group: "byedpi"

# @var byedpi_listen_ip:description: IP адрес для прослушивания
byedpi_listen_ip: "127.0.0.1"

# @var byedpi_listen_port:description: порт для прослушивания
byedpi_listen_port: 2080

# @var byedpi_options:description: дополнительные опции для byedpi
# @var byedpi_options:example: "-H:\"googlevideo.com youtube.com\" --oob 1 -An"
byedpi_options: "-H:\"googleapis.com\" -s1 -r1+s -An -H:\"ggpht.com googlevideo.com youtube.com youtu.be ytimg.com\" -o1 -r-5+se"
...
