---
- name: Update banner files
  ansible.builtin.copy:
    src: .
    dest: /etc/update-motd.d/
    mode: 0755
  become: true
  tags: motd

- name: Update motd
  command: update-motd
  become: true
  tags: motd
