---
- name: Install dwm package
  ansible.builtin.apt:
    deb: "{{ 'https://github.com/heldner/dwm-deb/releases/download/' +
      dwm_version + '/dwm_' + dwm_deb_version + '_amd64.deb' }}"
  when: >
    (ansible_facts.packages['dwm'] is defined and
    ansible_facts.packages['dwm'][0]['version'] != dwm_deb_version) or
    ansible_facts.packages['dwm'] is not defined
  become: true
  tags: dwm

- name: Create dwm actions dir
  ansible.builtin.file:
    state: 'directory'
    path: '{{ ansible_user_dir }}/.dwm/actions'
    mode: '0755'
  tags: dwm

- name: Copy dwm actions
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: '{{ ansible_user_dir }}/.dwm/actions/{{ item.path }}'
    mode: '0755'
  with_community.general.filetree: "files/actions/"
  tags: dwm

- name: Update wallpaper every hour
  ansible.builtin.cron:
    name: update wallpaper
    job: '{{ dmw_home }}/actions/update-wallpaper --cron'
    minute: '0'
  tags: dwm
