---
- block:

    - name: Install feh
      ansible.builtin.package:
        state: present
        name: feh
      become: true

    - name: Create feh config dir
      ansible.builtin.file:
        state: directory
        path: '{{ ansible_user_dir }}/.config/feh'
        mode: "0755"

    - name: Copy feh config
      ansible.builtin.copy:
        src: themes
        dest: '{{ ansible_user_dir }}/.config/feh/themes'
        mode: "0644"

  tags: feh

- name: Copy feh desktopfile
  ansible.builtin.copy:
    src: 'feh.desktop'
    dest: "{{ ansible_user_dir + '/.local/share/applications/feh.desktop' }}"
    mode: '0644'
  tags: feh

- name: Get default image viewer
  ansible.builtin.command: xdg-mime query default image/jpeg
  changed_when: false
  register: _default_viewer
  tags: feh

- name: Set default image viewer
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  when: _default_viewer.stdout != 'feh.desktop'
  notify: Set default picture viewer feh
  tags: feh
