---
galaxy_info:
  author: Stanislav Korolev
  description: install goimapnotify as user systemd service
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: package_facts
