---
- name: Install ppp and sstpc
  ansible.builtin.package:
    name:
      - ppp
      - sstp-client
    state: present
  become: true

- name: Create ppp provider config
  ansible.builtin.template:
    src: ppp.j2
    dest: '/etc/ppp/peers/{{ sstp_provider }}'
    mode: 0600
  become: true

- name: Create ip up script
  ansible.builtin.template:
    src: ip-up-routes.j2
    dest: '/etc/ppp/ip-up.d/{{ sstp_provider }}-routes'
    mode: 0755
  become: true
