---
galaxy_info:
  author: Stanislav Korolev
  description: install Xfce DE
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
