---
- name: Download spt package
  ansible.builtin.get_url:
    url: https://github.com/heldner/spt-deb/releases/download/{{ spt_version }}/spt_{{ spt_version }}-2_amd64.deb
    dest: /tmp/spt.deb
    mode: '0644'
  become: true
  tags: spt

- name: Install spt package
  ansible.builtin.apt:
    state: present
    deb: /tmp/spt.deb
  become: true
  tags: spt

- name: Copy mpv action for dwm
  ansible.builtin.import_role:
    name: dwm
    tasks_from: copy_action
  vars:
    dwm_actions:
      - action/spt
  tags: spt
