---
- name: Install libvirt packages
  ansible.builtin.package:
    state: present
    name:
      - dnsmasq-base
      - gir1.2-spiceclientgtk-3.0
      - libvirt-clients
      - libvirt-daemon-system
      - spice-client-gtk
      - qemu-system
      - virt-manager
      - virt-viewer
  become: true
  tags: libvirt

- name: Create link uuidgen
  ansible.builtin.file:
    state: link
    src: /usr/bin/dbus-uuidgen
    dest: /usr/local/bin/uuidgen
  become: true
  tags: libvirt

- name: Enable and start libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
  become: true
  tags: libvirt

- name: Add current user to libvirt group
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: libvirt
    append: true
  become: true
  tags: libvirt
