---
- name: Install libvirt packages
  ansible.builtin.package:
    state: present
    name:
      - dnsmasq-base
      - gir1.2-spiceclientgtk-3.0
      - libvirt-clients
      - libvirt-daemon-system
      - python3-libvirt
      - python3-lxml
      - qemu-system
      - qemu-utils
      - spice-client-gtk
      - virt-manager
      - virt-viewer
  become: true
  tags: libvirt

- name: Create link uuidgen
  ansible.builtin.file:
    state: link
    src: /usr/bin/dbus-uuidgen
    dest: /usr/local/bin/uuidgen
  become: true
  tags: libvirt

- name: Enable and start libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true
  become: true
  tags: libvirt

- name: Add current user to libvirt group
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: libvirt
    append: true
  become: true
  tags: libvirt

- name: Make default net active
  community.libvirt.virt_net:
    name: default
    state: active
  become: true
  tags: libvirt

- name: Make default net autostart
  community.libvirt.virt_net:
    name: default
    autostart: true
  become: true
  tags: libvirt

- name: Define a new storage pool
  community.libvirt.virt_pool:
    command: define
    name: vms
    xml: '{{ lookup("template", "pool.xml.j2") }}'
  become: true
  notify:
    - Enable storage pool
    - Enable autostart storage pool
  tags: libvirt

- name: Flush libvirt handlers
  meta: flush_handlers
  tags: libvirt
