---
- name: Install libvirt packages
  ansible.builtin.package:
    state: present
    name:
      - gir1.2-spiceclientgtk-3.0
      - libvirt-clients
      - libvirt-daemon
      - virt-manager
      - virt-viewer
      - spice-client-gtk
  become: true

- name: Create link uuidgen
  ansible.builtin.file:
    state: link
    src: /usr/bin/dbus-uuidgen
    dest: /usr/local/bin/uuidgen
  become: true
