---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install laptop specific tools
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
