---
- name: Include sshd tasks
  ansible.builtin.include_tasks: ssh_server.yml
  tags:
    - ssh
    - ssh_server

- name: Include ssh client tasks
  ansible.builtin.include_tasks: ssh_client.yml
  tags:
    - ssh
    - ssh_client
