---
- name: Install openssh-client
  ansible.builtin.package:
    state: present
    name:
      - autossh
      - keychain
      - libpam-ssh
      - openssh-client
  tags:
    - ssh
  become: true

- name: Create ssh dir
  ansible.builtin.file:
    state: directory
    path: '{{ ansible_user_dir }}/.ssh'
    mode: 0700

- name: Copy ssh config
  ansible.builtin.template:
    src: 'ssh_config.j2'
    dest: '{{ ansible_user_dir }}/.ssh/config'
    mode: 0640
  tags:
    - ssh
    - config

- name: Copy ssh tunnel script
  ansible.builtin.template:
    src: 'tunnel'
    dest: '{{ ansible_user_dir }}/.local/bin/tunnel'
    mode: 0755
  tags:
    - ssh
    - config
