---
- name: Install openssh-client
  ansible.builtin.package:
    state: present
    name:
      - openssh-server
      - libpam-google-authenticator
  tags:
    - ssh
    - ssh_server
  become: true

- name: Copy sshd config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: '/etc/ssh/sshd_config'
    mode: '0644'
  notify: Restart sshd
  become: true
  tags:
    - ssh
    - ssh_server

- name: Flush sshd handlers
  meta: flush_handlers
  tags:
    - ssh
    - ssh_server
