---
- name: Download slock package
  ansible.builtin.apt:
    deb: https://github.com/heldner/slock-deb/releases/download/{{ slock_version }}/slock_{{ slock_deb_version }}_amd64.deb
  when: >
    (ansible_facts.packages['slock'] is defined and
    ansible_facts.packages['slock'][0]['version'] != slock_deb_version) or
    ansible_facts.packages['slock'] is not defined
  become: true
  tags: slock

- name: Locker service machine before suspend
  ansible.builtin.template:
    src: slock.service.j2
    dest: /lib/systemd/system/slock.service
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true
  tags: slock

- name: Enable slock unit
  ansible.builtin.service:
    name: slock
    enabled: true
    daemon_reload: true
  become: true
  tags: slock
