---
# vim:ft=ansible:

# Install any python system dependencies.
# TOOD handle for RPM systems
- name: install python-dev
  pkg:
    name: {{ item }}
    state: present
  with_items:
    - python-dev
    - python-pip

- name: install virtualenv package
  pip: name=virtualenv

- name: add deploy_user
  user: name={{ deploy_user }} system=yes append=yes

- include: deploy.yml
  tags:
    - deploy
