---
- name: Create local bin
  ansible.builtin.file:
    state: directory
    path: '{{ ansible_user_dir }}/.local/bin'
    mode: "0755"
  tags: local_bin

- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: '{{ ansible_user_dir }}/.local/bin/{{ item.path }}'
    mode: '0755'
  with_community.general.filetree: "files/"
  tags: local_bin
