---
- name: Install podman
  ansible.builtin.package:
    state: present
    name:
      - uidmap
      - slirp4netns
      - podman
  become: true

- name: Copy config
  ansible.builtin.template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
  become: true
