---
- name: Install portsentry
  ansible.builtin.package:
    state: present
    name: portsentry
  tags: portsentry
  become: true

- name: Allow tcp portsentry
  ansible.builtin.iptables:
    chain: INPUT
    match_set: portsentry_tcp
    match_set_flags: dst
    protocol: tcp
    jump: ACCEPT
  become: true
  tags: portsentry

- name: Allow udp portsentry
  ansible.builtin.iptables:
    chain: INPUT
    match_set: portsentry_udp
    match_set_flags: dst
    protocol: udp
    jump: ACCEPT
  become: true
  tags: portsentry

- name: Drop portsentry ipset
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    match_set: portsentry_deny_hosts
    match_set_flags: src
    jump: DROP
  become: true
  tags: portsentry

- name: Copy portsentry config
  ansible.builtin.template:
    src: portsentry.conf.j2
    dest: /etc/portsentry/portsentry.conf
    mode: "0644"
  become: true
  notify: Restart portsentry
  tags: portsentry

- name: Generate ipset for portsentry
  ansible.builtin.import_role:
    name: iptables
    tasks_from: gen_ipset
  vars:
    ipset_name: portsentry
    ipset_tables:
      - name: portsentry_tcp
        set_option: bitmap:port range 0-65535
        items: "{{ portsentry_tcp_ports.split(',') }}"
      - name: portsentry_udp
        set_option: bitmap:port range 0-65535
        items: "{{ portsentry_udp_ports.split(',') }}"
      - name: portsentry_deny_hosts
        set_option: hash:ip timeout 86400
  tags: portsentry
