---
- block:
    - name: Install sxhkd
      ansible.builtin.package:
        name: sxhkd
        state: present
      become: true

    - name: Create config dir
      ansible.builtin.file:
        state: directory
        path: '{{ ansible_env.HOME }}/.config/sxhkd'
        mode: "0755"

    - name: Copy sxhkdrc config
      ansible.builtin.template:
        src: 'sxhkdrc.j2'
        dest: '{{ ansible_env.HOME }}/.config/sxhkd/sxhkdrc'
        mode: "0640"
      notify: Reload sxhkd

  tags:
    - xorg
    - sxhkd

- name: Flush sxhkd handlers
  meta: flush_handlers
  tags: sxhkd
