---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install [bird2](https://bird.network.cz/?index) routing daemon
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
