---
- name: Copy logind.conf disable suspend at close
  ansible.builtin.copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf
    mode: "0755"

- name: Ensure tp smapi installed
  ansible.builtin.package:
    state: present
    name:
      - intel-microcode
      - rfkill
      - tp-smapi-dkms
  become: true

- name: Copy battery checker script
  ansible.builtin.copy:
    src: batt_check
    dest: /usr/local/bin/batt_check
    mode: "0755"
  become: true

- name: Add cronjob battery checker
  ansible.builtin.cron:
    name: battery checker
    job: /usr/local/bin/batt_check
    minute: '*/5'
  become: true

- name: Locker service machine before suspend
  ansible.builtin.template:
    src: slock.service.j2
    dest: /lib/systemd/system/slock.service
    owner: 'root'
    group: 'root'
    mode: '"0644"'
  become: true

- name: Enable slock unit
  ansible.builtin.service:
    name: slock
    enabled: true
    daemon_reload: true
  become: true
