---
#
# Description
#  the `ferm` package need to be at least version 2.4
#  to support @preserve directive
#  if is old for Ubuntu 14 and even 16, so install it from S3
# see DVPS-15610

- name: Install ipset and iptables
  ansible.builtin.apt:
    name:
      - ipset
      - iptables
    cache_valid_time: 600
    update_cache: true
  tags:
    - iptables

- name: Download ferm package
  ansible.builtin.uri:
    url: https://tradingview-packages.s3-us-west-2.amazonaws.com/ferm-2.4-1.deb
    dest: /tmp/ferm-2.4-1.deb
  tags:
    - iptables
  check_mode: false

- name: Install ferm package
  ansible.builtin.apt:
    deb: /tmp/ferm-2.4-1.deb
  tags:
    - iptables
  check_mode: false

- name: Cleanup ferm package file
  ansible.builtin.file:
    path: /tmp/ferm-2.4-1.deb
    state: absent
  check_mode: false
  tags:
    - iptables

- name: Remove iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: absent
    purge: true
    force: true
  tags:
    - iptables

- name: Copy ipset_reload
  ansible.builtin.copy:
    src: ipset-reload.sh
    dest: /usr/local/bin/ipset-reload.sh
    mode: u=rxw,g=r,o=r
    owner: root
    group: root
  tags:
    - iptables

- name: Create ipset tables
  ansible.builtin.template:
    src: ipset.tables.j2
    dest: /etc/ipset.tables
  notify:
    - Reload ipset tables
    - Fill up ipsets
    - Reload ferm
  tags:
    - ipset
    - iptables

- name: Copy /etc/default/ferm
  ansible.builtin.copy:
    src: default-ferm
    dest: /etc/default/ferm
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Reload ferm
  tags:
    - ferm
    - iptables

- name: Generate /etc/ferm/ferm.conf
  ansible.builtin.template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    mode: 0644
    owner: root
    group: root
  notify: Reload ferm
  tags:
    - ferm
    - iptables

- include: autoban.yml
  when: ipset_tables.auto_ban is defined
  tags:
    - iptables
    - autoban

- include: healthcheck.yml
  when: external_healthcheck is defined

- name: Flush iptables handlers
  meta: flush_handlers
