---
- name: Restart nginx
  ansible.builtin.command:
    cmd: nginx -t
  become: true
  notify: Restart nginx stage 2
  tags: nginx

- name: Restart nginx stage 2
  ansible.builtin.command:
    cmd: nginx -s reload
  become: true
  tags: nginx
