---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install neovim text editor
  company: RootIT
  license: ISC
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 11

  galaxy_tags: [vim, neovim, nvim, editor, text]

dependencies:
  - role: apt
  - role: editorconfig
