---
zplug_plugins:
  - name: zsh-users/zsh-syntax-highlighting
    opts: "defer:2"
  - name: romkatv/powerlevel10k
    opts: "as:theme, depth:1"
  - name: changyuheng/fz
    opts: "defer:1"
  - name: rupa/z
    opts: "use:z.sh"
  - name: Tarrasch/zsh-autoenv
  - name: pasky/speedread
    opts: "use:speedread.plugin.zsh"
  - name: joshskidmore/zsh-fzf-history-search
    config:
      - >-
        ZSH_FZF_HISTORY_SEARCH_FZF_ARGS="+s +m -x
        --preview-window=hidden --layout=reverse --color=hl+:magenta"
