#!/bin/sh

ff_bwrap() {
  uid=$(id -u)
  exec bwrap \
    --bind /home/"$USER"/.cache/mozilla /home/"$USER"/.cache/mozilla \
    --bind /home/"$USER"/.mozilla /home/"$USER"/.mozilla \
    --bind /home/"$USER"/Downloads /home/"$USER"/Downloads \
    --dev /dev \
    --dev-bind /dev/dri /dev/dri \
    --die-with-parent \
    --dir /run/user/"$uid" \
    --hostname RESTRICTED \
    --new-session \
    --proc /proc \
    --ro-bind /etc/ca-certificates /etc/ca-certificates \
    --ro-bind /etc/fonts /etc/fonts \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --ro-bind /etc/ssl /etc/ssl \
    --ro-bind /run/user/"$uid"/pulse /run/user/"$uid"/pulse \
    --ro-bind /sys/dev/char /sys/dev/char \
    --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
    --ro-bind /usr/bin /usr/bin \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
    --ro-bind /usr/share/pyshared /usr/share/pyshared \
    --ro-bind /usr/share/distro-info /usr/share/distro-info \
    --ro-bind /usr/share/applications /usr/share/applications \
    --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
    --ro-bind /usr/share/drirc.d /usr/share/drirc.d \
    --ro-bind /usr/share/fontconfig /usr/share/fontconfig \
    --ro-bind /usr/share/fonts /usr/share/fonts \
    --ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
    --ro-bind /usr/share/glvnd /usr/share/glvnd \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/libdrm /usr/share/libdrm \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /home/"$USER"/.password-store /home/"$USER"/.password-store \
    --setenv GTK_THEME Adwaita:dark \
    --setenv HOME /home/"$USER" \
    --setenv PATH /usr/bin \
    --share-net \
    --symlink usr/bin /bin \
    --symlink usr/bin /sbin \
    --symlink usr/lib /lib \
    --symlink usr/lib64 /lib64 \
    --tmpfs /tmp \
    --unshare-cgroup-try \
    --unshare-pid \
    --unshare-user-try \
    --unshare-uts \
    /usr/bin/firefox
}

ff_bwrap &
