---
- name: Set packages list
  ansible.builtin.set_fact:
    git_pkgs: "{{ __pkgs +
      ([ 'git-extras' ] if ansible_distribution != 'OpenBSD' else []) }}"
  vars:
    __pkgs: [git]
  tags: git

- name: Ensure git package installed
  ansible.builtin.package:
    state: present
    name: '{{ git_pkgs }}'
    update_cache: true
  tags: git
  become: true

- name: Install .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: '{{ ansible_user_dir}}/.gitconfig'
    owner: '{{ ansible_user_id }}'
    mode: "0640"
  tags: git

- name: Install git custom configs
  ansible.builtin.template:
    src: gitconfig_custom.j2
    dest: '{{ ansible_user_dir}}/.gitconfig_{{ item.config_name }}'
    owner: '{{ ansible_user_id }}'
    mode: "0640"
  loop: '{{ git_custom_configs }}'
  when: git_custom_configs is defined
  tags: git
