---
- name: Set packages list
  ansible.builtin.set_fact:
    git_pkgs: "{{ __pkgs +
      ([ 'git-extras' ] if ansible_distribution != 'OpenBSD' else []) }}"
  vars:
    __pkgs: [git]

- name: Ensure git package installed
  ansible.builtin.package:
    state: present
    name: '{{ git_pkgs }}'
  become: true

- name: Install .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: '{{ ansible_user_dir}}/.gitconfig'
    owner: '{{ ansible_user_id }}'
    mode: 0640
