---
- name: Generate CA cert
  ansible.builtin.include_tasks: gen_ca.yml
  when: not acme_enabled
  tags: certificates

- name: Generate and sign certificate
  ansible.builtin.include_tasks: gen_cert.yml
  when: not acme_enabled
  tags: certificates

- name: Generate acme cert
  ansible.builtin.include_tasks: acme.yml
  when: acme_enabled
  tags:
    - certificates
    - acme
