---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install simple screen locker utility for X.
  company: RootIT
  license: ISC
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - all
