---
- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  tags: bluetooth

- name: Restart bluetooth
  ansible.builtin.service:
    name: bluetooth
    state: restarted
  become: true
  tags: bluetooth
