---
- name: Install iwd package
  ansible.builtin.package:
    state: present
    name: iwd
  become: true
  tags: iwd

- name: Copy iwd config
  ansible.builtin.copy:
    src: iwd_main.conf
    dest: /etc/iwd/main.conf
    mode: "0644"
  become: true
  notify: Restart iwd
  tags:
    - iwd
    - configure

- name: Flush iwd handlers
  meta: flush_handlers
  tags: iwd

- name: Enable and start
  ansible.builtin.systemd:
    name: iwd
    enabled: true
    state: started

- name: Copy iwctl desktopfile
  ansible.builtin.copy:
    src: "iwctl.desktop"
    dest: "/usr/share/applications/iwctl.desktop"
    mode: "0644"
  become: true
  tags:
    - iwd
    - configure
