---
- name: Copy config
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
  loop:
    - src: mpd.conf.j2
      dst: '{{ mpd_home_dir }}/mpd.conf'
    - src: ncmpcpp_config.j2
      dst: '{{ ansible_user_dir }}/.config/ncmpcpp/config'
  register: _mpd_config

- name: Copy playlists
  ansible.builtin.synchronize:
    archive: false
    src: 'playlists/'
    delete: true
    dest: "{{ ansible_user_dir }}/Music/playlists"
    recursive: true
    rsync_opts: ["--times"]
    use_ssh_args: true
