---
- name: Copy config
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
  loop:
    - src: mpd.conf.j2
      dst: '{{ mpd_home_dir }}/mpd.conf'
    - src: ncmpcpp_config.j2
      dst: '{{ ansible_user_dir }}/.config/ncmpcpp/config'
  register: _mpd_config
  tags:
    - mpd
    - configure

- name: Copy playlists
  ansible.builtin.synchronize:
    archive: false
    src: 'playlists/'
    delete: true
    dest: "{{ ansible_user_dir }}/Music/playlists"
    recursive: true
    rsync_opts: ["--times"]
    use_ssh_args: true
  tags:
    - mpd
    - configure

- name: Copy ncmpcpp desktopfile
  ansible.builtin.copy:
    src: "ncmpcpp.desktop"
    dest: "/usr/share/applications/ncmpcpp.desktop"
    mode: "0644"
  become: true
  tags:
    - mpd
    - configure
