---
- name: Install mpd
  ansible.builtin.apt:
    name:
      - mpc
      - mpd
      - mpdris2
      - ncmpcpp
      - libmpdclient2
    state: present
  become: true
  tags: mpd

- name: Create dirs
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/Music"
    - "{{ ansible_user_dir }}/Music/playlists"
    - "{{ ansible_user_dir }}/.config/mpd"
    - "{{ ansible_user_dir }}/.config/ncmpcpp"
    - "{{ ansible_user_dir }}/.config/mpDris2"
  tags: mpd

- name: Copy config
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    mode: '0644'
  loop:
    - src: mpd.conf.j2
      dst: '{{ mpd_home_dir }}/mpd.conf'
    - src: ncmpcpp_config.j2
      dst: '{{ ansible_user_dir }}/.config/ncmpcpp/config'
  notify: Restart mpd
  tags: mpd

- name: Copy mpDris2 config
  ansible.builtin.template:
    src: 'mpDris2.conf.j2'
    dest: '{{ ansible_user_dir }}/.config/mpDris2/mpDris2.conf'
    mode: '0644'
  notify: Restart mpDris2
  tags: mpd

- name: Copy playlists
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/Music/playlists/{{ item.path }}"
    mode: '0644'
  with_community.general.filetree: "files/playlists"
  tags: mpd

- name: Copy ncmpcpp desktopfile
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    mode: "0644"
  loop:
    - src: ncmpcpp_bindings
      dst: '{{ ansible_user_dir }}/.config/ncmpcpp/bindings'
    - src: 'ncmpcpp.desktop'
      dst: '{{ ansible_user_dir }}/.local/share/applications/ncmpcpp.desktop'
  tags: mpd

- name: Create systemd mpDris2 override
  ansible.builtin.file:
    state: absent
    path: '{{ ansible_user_dir }}/.config/systemd/user/mpDris2.service.d'
    mode: '0755'
  tags: mpd

- name: Disable system mpd
  ansible.builtin.service:
    name: mpd
    enabled: false
    state: stopped
  become: true
  tags: mpd

- name: Start mpd and mpDris2
  ansible.builtin.systemd:
    scope: user
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - mpd
    - mpDris2
  tags: mpd

- name: Flush mpd handlers
  ansible.builtin.meta: flush_handlers
  tags: mpd
