---
- name: Install
  ansible.builtin.include_tasks: install.yml
  tags:
    - mpd
    - install

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - mpd
    - configure

- name: Start
  ansible.builtin.include_tasks: start.yml
  tags:
    - mpd
    - start
