---
- name: Disable system mpd
  ansible.builtin.systemd:
    name: mpd
    enabled: false
    state: stopped
  become: true

- name: Start mpd
  ansible.builtin.systemd:
    scope: user
    name: mpd
    enabled: true
    state: started
  register: _start_mpd

- name: Restart mpd
  ansible.builtin.systemd:
    scope: user
    name: mpd
    state: restarted
  when:
    - _mpd_config.changed
    - not _start_mpd.changed
