---
- name: Install nftables
  ansible.builtin.package:
    name:
      - nftables
    cache_valid_time: 600
  become: true
  tags: nftables

- name: Copy nftables rules
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0744"
  become: true
  notify: Reload nft
  tags: nftables

- name: Enable service nftables
  ansible.builtin.service:
    name: nftables
    enabled: true
  become: true
  tags: nftables

- name: Flush nftables handlers
  meta: flush_handlers
  tags: nftables
