#!/bin/bash

lock="/var/$(basename "$0").lock"
control_file="/sys/class/backlight/intel_backlight/brightness"
STEP='150'

fetch_value () {
  cat $control_file
}

decrease () {
  curr="$1"
  echo $(( $curr - $STEP ))
}

increase () {
  curr="$1"
  echo $(( $curr + $STEP ))
}

update_bright () {
  curr_val=$(fetch_value)
  new_val="$(increase $curr_val)"
  echo "$new_val" |tee "$control_file"
}

update_bright
