---
- name: Install v2ray
  ansible.builtin.package:
    state: present
    name: v2ray
  tags: v2ray
  become: true

- name: Create a v2ray.service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/v2ray.service.d
    owner: root
    group: root
    mode: 0755
    state: directory
  when: v2ray_mode != 'client'
  become: true
  tags: v2ray

- name: Set up v2ray.service override
  ansible.builtin.ini_file:
    dest: /etc/systemd/system/v2ray.service.d/chmod_socket.conf
    owner: root
    group: root
    mode: 0644
    section: Service
    option: ExecStartPost
    value: sleep 4 ; /usr/bin/chmod 0666 {{ v2ray_server_socket }}
  notify: Systemctl daemon-reload
  when: v2ray_mode != 'client'
  become: true
  tags: v2ray

- name: Flush v2ray handlers
  meta: flush_handlers
  when: v2ray_mode != 'client'
  tags: v2ray

- name: Generate v2ray config
  ansible.builtin.copy:
    content: "{{ lookup('template',
      'templates/v2ray-{{ v2ray_mode }}.json.j2') | to_nice_json('  ') }}"
    dest: /etc/v2ray/config.json
    mode: '0644'
    owner: 'root'
    group: 'root'
  become: true
  notify: Restart v2ray
  tags: v2ray

- name: Enable and start v2ray
  ansible.builtin.service:
    name: v2ray
    enabled: true
    state: started
  become: true
  tags: v2ray

- name: Configure nginx
  ansible.builtin.import_role:
    name: nginx
    tasks_from: gen_config
  vars:
    nginx_template: v2ray_nginx.conf.j2
  when: v2ray_mode != 'client'
  tags:
    - nginx
    - v2ray
