#!/bin/sh
if [ "$1" = '--video' ]; then
  VIDEO_OPT="--dev-bind /dev/video1 /dev/video1
  --dev-bind /dev/video0 /dev/video0"
  shift
fi
exec bwrap \
     --ro-bind /usr/lib/ungoogled-chromium /usr/lib/ungoogled-chromium \
     --ro-bind /usr/bin/ungoogled-chromium /usr/bin/ungoogled-chromium \
     --ro-bind /usr/bin/sh /usr/bin/sh \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     --proc /proc \
     --dev /dev \
     $VIDEO_OPT \
     --dev-bind /dev/char /dev/char \
     --dev-bind /dev/dri /dev/dri \
     --ro-bind-try /sys/bus/usb /sys/bus/usb \
     --ro-bind-try /sys/dev /sys/dev \
     --ro-bind-try /sys/devices /sys/devices \
     --ro-bind /etc/passwd /etc/passwd \
     --ro-bind /etc/group /etc/group \
     --ro-bind /etc/hostname /etc/hostname \
     --ro-bind /etc/hosts /etc/hosts \
     --ro-bind /etc/localtime /etc/localtime \
     --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
     --ro-bind /run/dbus/system_bus_socket /run/dbus/system_bus_socket \
     --ro-bind /run/user/"$(id -u)"/bus /run/user/"$(id -u)"/bus \
     --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
     --ro-bind-try /etc/xdg /etc/xdg \
     --ro-bind-try /etc/gtk-2.0 /etc/gtk-2.0 \
     --ro-bind-try /etc/gtk-3.0 /etc/gtk-3.0 \
     --ro-bind-try /etc/fonts /etc/fonts \
     --ro-bind-try /etc/mime.types /etc/mime.types \
     --ro-bind-try /etc/alsa /etc/alsa \
     --ro-bind-try ~/Pictures/Screenshots ~/Pictures/Screenshots \
     --tmpfs /tmp \
     --bind-try "$TEMPDIR" "$TEMPDIR" \
     --dir "$XDG_RUNTIME_DIR" \
     --ro-bind-try "${XDG_RUNTIME_DIR}/pipewire-0" "${XDG_RUNTIME_DIR}/pipewire-0" \
     --ro-bind-try "${XDG_RUNTIME_DIR}/pipewire-0.lock" "${XDG_RUNTIME_DIR}/pipewire-0.lock" \
     --ro-bind-try "${XDG_RUNTIME_DIR}/pulse" "${XDG_RUNTIME_DIR}/pulse" \
     --bind-try ~/Downloads ~/Downloads \
     --bind-try ~/.cache/chromium ~/.cache/chromium \
     --bind ~/.config/chromium ~/.config/chromium \
     --unshare-all \
     --share-net \
     --new-session \
     --hostname mypc \
     /usr/lib/ungoogled-chromium/chromium "$@" > /dev/null 2>&1
