---
- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  become: true

- name: copy tmux conf
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ ansible_env.HOME }}/.{{ item }}'
    mode: "0644"
  loop:
    - tmux.conf
    - gray.tmuxtheme
  tags:
    - tmux
    - config
