---
- name: Reload thinkpad_acpi module
  ansible.builtin.command:
    cmd: rmmod thinkpad_acpi
  notify: Load thinkpad_acpi module
  become: true

- name: Load thinkpad_acpi module
  ansible.builtin.command:
    cmd: modprobe thinkpad_acpi
  become: true

- name: Restart thinkfan
  ansible.builtin.service:
    name: thinkfan
    state: restarted
  become: true
