#!/bin/sh
#
# update mail counter file

MAIL_COUNTER="$HOME/.new_mail_counter"
MAILDIR=${HOME}/Private/Mail

update_counter() {
  find "$MAILDIR" -type f -regex '.*inbox\/new.*' \
    | wc -l
}

num=$(update_counter)
if [ "$num" -ne 0 ]; then
  echo "$num" > "$MAIL_COUNTER"
else
  if [ -f "$MAIL_COUNTER" ]; then
    rm "$MAIL_COUNTER"
  fi
fi
