#!/bin/sh
#
# watch mail directory and update mail counter file

MAIL_COUNTER="$HOME/.new_mail_counter"
MAILDIR="${HOME}/Private/Mail"

mail_watcher () {
  inotifywait \
    --recursive "$MAILDIR" \
    --event DELETE,create \
    --include ".*cur" >/dev/null 2>&1
}

update_counter() {
  find ~/Private/Mail/ -type f -regex '.*inbox\/new.*' \
    | wc -l > "$MAIL_COUNTER"
}

sync_mail() {
  mbsync -a >/dev/null 2>&1
}

while sync_mail; do
  update_counter
  mail_watcher
  if readlink -e "$MAILDIR" > /dev/null; then
    sleep 0.5
  else
    sleep 60
  fi
done
