---

galaxy_info:
  role_name: autossh
  author: Javier Palacios
  description: Deploy & configure autossh to manage ssh tunnels
  company: DEVO Inc.
  license: GPL-3.0
  min_ansible_version: 2.0.0
  galaxy_tags:

dependencies: []

