---
- name: Install shadowsocks-libev
  ansible.builtin.package:
    state: present
    name:
      - shadowsocks-libev
      - shadowsocks-v2ray-plugin
  tags: shadowsocks
  become: true

- name: Create shadowsocks user
  ansible.builtin.user:
    name: shadowsocks
    home: /nonexistent
    shell: /sbin/nologin
  tags: shadowsocks
  become: true

- name: Disable default ss service
  ansible.builtin.service:
    name: "shadowsocks-libev"
    state: stopped
    enabled: false
  become: true

- ansible.builtin.include_tasks: "{{ shadowsocks_mode }}.yml"
