---
- name: Copy shadowsocks config
  ansible.builtin.template:
    src: "server-config.json.j2"
    dest: /etc/shadowsocks-libev/config.json
    owner: shadowsocks
    mode: 0644
  tags: [shadowsocks, config]
  notify: Restart shadowsocks-libev
  become: true

- name: Copy shadowsocks default
  ansible.builtin.template:
    src: "default.j2"
    dest: /etc/default/shadowsocks-libev
    mode: 0644
  tags: [shadowsocks, config]
  notify: Restart shadowsocks-libev
  become: true

- name: Start shadowsocks-libev
  ansible.builtin.service:
    name: shadowsocks-libev
    state: started
    enabled: true
  become: true
