---
- name: Replace systemd unit
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/shadowsocks-libev-server@.service.d
  become: true

- name: Copy shadowsocks systemd config
  ansible.builtin.template:
    src: "systemd.conf.j2"
    dest: /etc/systemd/system/shadowsocks-libev-server@.service.d/custom.conf
  become: true

- name: Force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Copy shadowsocks config
  ansible.builtin.template:
    src: "{{ shadowsocks_mode }}-config.json.j2"
    dest: "/etc/shadowsocks-libev/{{ shadowsocks_mode }}.json"
    owner: shadowsocks
    mode: "0640"
  tags: [shadowsocks, config]
  notify: Restart shadowsocks-server
  no_log: "{{ nolog | default('true') | bool }}"
  become: true

- name: Enable and start server ss
  ansible.builtin.service:
    name: "shadowsocks-libev-server@{{ shadowsocks_mode }}"
    state: started
    enabled: true
  become: true
