---
- name: Ensure common packages installed
  ansible.builtin.package:
    state: present
    name:
      - acl
      - at
      - bwm-ng
      - console-data
      - curl
      - dconf-service
      - debsums
      - dirmngr
      - duf
      - exfatprogs
      - fonts-powerline
      - gifsicle
      - htop
      - ipython3
      - jnettop
      - keychain
      - lsd
      - man
      - ncdu
      - p7zip-full
      - python3-pip
      - ripgrep
      - rsync
      - strace
      - sysstat
      - tcpdump
      - w3m
      - zbar-tools
  become: true

- name: Remove avahi
  ansible.builtin.apt:
    state: absent
    pkg:
      - avahi-autoipd
  become: true

- name: Include desktop tasks
  ansible.builtin.include_tasks: desktop.yml
  when: desktop_mode == true | bool
