---
- name: Ensure common packages installed
  ansible.builtin.package:
    state: present
    name:
      - acl
      - at
      - bat
      - bwm-ng
      - console-data
      - curl
      - dconf-service
      - debsums
      - dirmngr
      - dosfstools
      - duf
      - exfatprogs
      - fonts-hermit
      - fonts-powerline
      - ipython3
      - jnettop
      - keychain
      - man
      - nmap
      - ncdu
      - p7zip-full
      - python3-pip
      - ripgrep
      - rsync
      - shellcheck
      - strace
      - tcpdump
      - w3m
      - quilt
      - xkcdpass
      - zbar-tools
  become: true
  tags: common

- name: Remove avahi
  ansible.builtin.package:
    state: absent
    pkg: avahi-autoipd
  become: true
  tags: common

- name: Copy jenttop desktopfile
  ansible.builtin.copy:
    src: 'jnettop.desktop'
    dest: "{{ ansible_user_dir +
      '/.local/share/applications/jnettop.desktop' }}"
    mode: '0644'
  tags: common

- ansible.builtin.include_tasks: 'lsd.yml'
  tags: common

- name: Setup sudo
  ansible.builtin.include_role:
    name: sudo
    tasks_from: 'sudo_edit.yml'
  tags: common
