---
- name: Ensure common packages installed
  ansible.builtin.package:
    state: present
    name:
      - acl
      - alsa-utils
      - at
      - bluetooth
      - bluez
      - btrfs-progs
      - bwm-ng
      - console-data
      - curl
      - dconf-service
      - dirmngr
      - exfatprogs
      - f2fs-tools
      - firmware-iwlwifi
      - fonts-powerline
      - gifsicle
      - htop
      - ipython3
      - jnettop
      - keychain
      - libnotify-bin
      - man
      - ncdu
      - oathtool
      - pass
      - pass-extension-otp
      - pipewire-audio
      - pipewire-pulse
      - python3-pip
      - ripgrep
      - rsync
      - strace
      - tcpdump
      - w3m
      - zbar-tools
  become: true

- name: Remove avahi
  ansible.builtin.apt:
    state: absent
    pkg:
      - avahi-autoipd
  become: true
