---
- name: Download docker repo gpg key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"
  tags: docker
  become: true

- name: Add apt repository
  ansible.builtin.apt_repository:
    state: present
    filename: docker
    repo:
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
  tags: docker
  become: true

- name: Install docker
  ansible.builtin.package:
    state: present
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - docker-compose-plugin
  become: true
  tags: docker
