#!/bin/sh

CMD="$*"
OPTS='-t '

ssh_cmd () {
    if [ -x "$(which autossh)" ]; then
        echo 'autossh -M 0'
    else
        echo 'ssh'
    fi
}

host=$(cat ~/.ssh/config ~/.ssh/config.d/* 2>/dev/null \
    | awk '$2 !~ /^\*/ && /^Host/ {sub(/\*$/,""); print $2}' \
    | sort -u \
    | dmenu -p ssh:)

[ -z "$host" ] && exit

if pgrep -lf "$(ssh_cmd).*${host}$"; then
  kitty -1 ssh $OPTS $host "$CMD"
else
  kitty -1 $(ssh_cmd) $OPTS $host "$CMD"
fi
