---
- name: Ensure gocryptfs and pam packages present
  ansible.builtin.package:
    state: present
    pkg:
      - fuse3
      - gocryptfs
      - libpam-mount
      - libpam-mount-bin
  tags: gocryptfs
  become: true

- name: Copy pam_mount user config
  ansible.builtin.template:
    src: pam_mount.conf.xml.j2
    dest: '{{ ansible_user_dir }}/.pam_mount.conf.xml'
    mode: '0644'
  tags: gocryptfs

- name: Copy pam_mount system config
  ansible.builtin.copy:
    src: etc_security_pam_mount.conf.xml
    dest: '/etc/security/pam_mount.conf.xml'
    mode: '0644'
  become: true
  tags: gocryptfs

- name: Copy fuse.conf
  ansible.builtin.copy:
    src: 'fuse.conf'
    dest: '/etc/fuse.conf'
    mode: '0644'
  become: true
  tags: gocryptfs
