---
- name: Install gnupg
  ansible.builtin.package:
    state: present
    name:
      - gnupg
      - gnupg-utils
      - pinentry-curses
      - pinentry-gtk2
  tags: [gnupg, pgp, gpg]
  become: true

- name: Create config direcotyr
  ansible.builtin.file:
    state: directory
    dest: '{{ ansible_env.HOME }}/.gnupg'
    mode: 0700

- name: Copy gnupg configs
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ ansible_env.HOME }}/.gnupg/{{ item }}'
    mode: 0644
  loop:
    - gpg.conf
    - gpg-agent.conf
