---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags:
    - browser
    - librewolf

- name: Update alternatives, install librewolf
  ansible.builtin.command: |
    update-alternatives --install /usr/bin/x-www-browser
    x-www-browser {{ librewolf_bwrap_path }} 10
  become: true
  tags:
    - browser
    - librewolf
