---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags:
    - browser
    - librewolf

- name: Update alternatives, install librewolf
  ansible.builtin.command: |
    update-alternatives --install /usr/bin/x-www-browser
    x-www-browser /usr/bin/librewolf 10
  become: true
  tags:
    - browser
    - librewolf

- name: Set default xdg browser librewolf
  ansible.builtin.command: |
    xdg-settings set default-web-browser librewolf.desktop
  become: true
  tags:
    - librewolf
