---
- name: copy udev rules
  copy:
    src: '{{item}}'
    dest: '/etc/udev/rules.d/90-{{item}}'
    mode: "0644"
  notify: reload udev rules
  tags:
    - udev
  with_items:
    - automount-by-label.rules
   #- wifi.rules
   #- backlight.rules

- name: copy automount script
  copy:
    src: 'automount-usb'
    dest: '/usr/local/bin/automount-usb'
    mode: "0755"
  tags:
    - udev
