---
- name: Copy udev rules
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/etc/udev/rules.d/90-{{item}}'
    mode: "0644"
  become: true
  loop:
    - automount-by-label.rules
  notify: Reload udev rules
  tags: udev

- name: Copy udev rules
  ansible.builtin.copy:
    src: 'usbmount.sh'
    dest: '/usr/bin/usbmount.sh'
    mode: '0755'
  become: true
  tags: udev

- name: Flush udev handlers
  meta: flush_handlers
  tags: udev
