---
- name: Set options for thinkpad_acpi module
  ansible.builtin.copy:
    src: thinkpad_acpi.conf
    dest: /etc/modprobe.d/thinkpad_acpi.conf
  notify: Reload thinkpad_acpi module
  become: true
  tags: thinkfan

- name: Install thinkfan
  ansible.builtin.package:
    state: present
    name: thinkfan
    policy_rc_d: 101
  become: true
  tags: thinkfan

- name: Generate thinkfan.conf
  ansible.builtin.template:
    src: thinkfan.conf.j2
    dest: /etc/thinkfan.conf
  notify: Restart thinkfan
  become: true
  tags: thinkfan

- name: Flush thinkfan handlers
  ansible.builtin.meta: flush_handlers
  tags: thinkfan

- name: Start thinkfan
  ansible.builtin.service:
    name: thinkfan
    state: started
    enabled: true
  become: true
  tags: thinkfan
