#!/bin/sh
#
# enable natural scrolling

thinkpad_mouse='Elan Touchpad'
xinput_res=$(xinput list)

get_id() {
  echo "$xinput_res" | awk -F '(\t|=)' '/'"$1"'/ {print $(NF-1)}'
}

if echo "$xinput_res" |grep -q "$thinkpad_mouse"; then
  xinput set-prop "$(get_id "$thinkpad_mouse")" 'libinput Natural Scrolling Enabled' 1
fi
