#!/bin/sh
#
# enable natural scrolling

DEVICE_LIST='
ckb1: CORSAIR IRONCLAW RGB Gaming Mouse vM
Corsair CORSAIR IRONCLAW RGB Gaming Mouse
CORSAIR HARPOON
SynPS/2 Synaptics TouchPad
'

#xinput_res=$(xinput list)
xinput_res=$(xinput --list --name-only)

get_id() {
  xinput list --id-only "$1"
}

enable_ns() {
  device="$1"
  if echo "$xinput_res" |grep -q -x "$device"; then
    xinput set-prop "$(get_id "$device")" \
      'libinput Natural Scrolling Enabled' 1
  fi
}

echo "$DEVICE_LIST" | while read -r dev; do
  [ -z "$dev" ] && continue
  enable_ns "$dev"
done
