#!/bin/sh
#
# enable natural scrolling

station_mouse='Microsoft Microsoft® Comfort Mouse 4500'
thinkpad_mouse='SynPS/2 Synaptics TouchPad'

xinput_res=$(xinput list)

if echo "$xinput_res" |grep -q "$station_mouse"; then
    xinput set-prop "pointer:$station_mouse" 'libinput Natural Scrolling Enabled' 1
fi
if echo "$xinput_res" |grep -q "$thinkpad_mouse"; then
    xinput set-prop "pointer:$thinkpad_mouse" "Synaptics Scrolling Distance" -110 -110
fi
