#!/bin/zsh

if [ $# -eq 0 ]; then
    files=( ./*.flac )
else
    files="$1"
fi

for file in ${files[@]}; do
    #echo "FILE: $file"
    ffmpeg -y -i "$file" -aq 0 -f mp3 -map_metadata 0 "${file%.*}.mp3";
done
