#!/usr/bin/env python3

'''
connect to remote oprenvpn server with user and password
password fetched from pass utility
'''

import argparse
import subprocess
import os
import sys
import pexpect

def mypass(pass_name):
    ''' Fetch password from pass manager '''
    print("fetch my pass")
    passout = subprocess.run(
        ['pass', pass_name],
        capture_output=True, check=True)
    pass_list = passout.stdout.split()
    return pass_list[0].decode()

def run_vpn(pwd, config_path, logall=False):
    ''' Run openvpn and bypass secrets '''
    print("RUN openvpn")
    child = pexpect.spawn('sudo openvpn --config {}'.format(config_path))
    if logall:
        child.logfile_read = sys.stdout.buffer
    child.expect('.*Enter Auth Username:.*')
    child.send("USERNAME\n")
    child.expect('.*Enter Auth Password:.*')
    child.send(pwd)
    child.send('\n')
    #child.expect('.*Initialization.*')
    return True

def parse_args():
    ''' parse input arguments '''
    parser = argparse.ArgumentParser(
        description='Run openvpn without user inpute')
    parser.add_argument('-f', dest='filename', default='',
                        help='openvpn file config')
    parser.add_argument('-p', dest='passname', default='',
                        help='name of passworid in pass utility')
    return parser.parse_args()

def check_file(filepath):
    ''' exit if no file '''
    if not os.path.exists(filepath):
        print("File not found {}".format(filepath))
        sys.exit(1)

if __name__ == '__main__':
    ARGS = parse_args()
    check_file(ARGS.filename)
    run_vpn(mypass(str(ARGS.passname)), str(ARGS.filename), True)
