#!/bin/sh

SCRIPTHOME="${HOME}/.games/quake3e"
exec "${SCRIPTHOME}/quake3e.x64" \
  +set vm_game 2 \
  +set fs_game cpma \
  +set ttycon 0 \
  +set com_hunkmegs 128 \
  +exec my.cfg \
  +connect x.woozymasta.ru 2> /dev/null
