#!/bin/sh

if lsmod | grep -q uvcvideo; then
  notify-send "Webcam" "currently enabled"
  if sudo rmmod uvcvideo; then
    notify-send "Webcam" "disabled"
  fi
else
  notify-send "Webcam" "currently disabled"
  if sudo modprobe uvcvideo; then
    notify-send "Webcam" "enabled"
  fi
fi
