#!/bin/sh

export DISPLAY=:0.0

usage () {
  echo "Usage: $(basename $0) <on|off|toggle|status>"
  exit 1
}

status () {
  xset -q | awk '/Monitor is/ { gsub(/^\s*/,""); print $0}'
}

toggle () {
  result=$(status)
  if echo $result | grep -q "On";then
    xset dpms force off
    sleep 2
  else
    xset dpms force on
  fi
}

case $1 in
    on)     xset dpms force on ;;
    off)    xset dpms force off ;;
    toggle) toggle ;;
    status) status ;;
    *)      usage ;;
esac
