#!/bin/sh

remote_addr=192.168.0.14
local_addr="10.1.0.1"
networks="10.0.34.0/24"


if ip l | grep ipip0; then
  sudo ip tunnel delete ipip0
fi
sudo ip tunnel add mode ipip remote $remote_addr
sudo ip addr add "${local_addr}/24" dev ipip0 #src $local_addr
sudo ip link set ipip0 up
for net in $networks; do
  sudo ip route add "$net" dev ipip0 #src $local_addr
done
sudo sysctl -w net.ipv4.ip_forward=1
sudo ip route add 192.168.122.0/24 dev ipip0 scope link

local_iptables() {
  sudo iptables -D LIBVIRT_FWO -i virbr0 -j REJECT --reject-with icmp-port-unreachable
  sudo iptables -D LIBVIRT_FWI -o virbr0 -j REJECT --reject-with icmp-port-unreachable
}

local_iptables

