---
- hosts: openwrt
  remote_user: root
  gather_facts: false
  strategy: free
  vars:
    openwrt_scp: /usr/bin/scp -O
    openwrt_scp_if_ssh: smart
    openwrt_install_recommended_packages: false
  roles:
    - gekmihesg.openwrt
    - banana
