---
- hosts: all
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - apt
    - acpi
    - bluetooth
    - common
    - chromium
    - console-setup
    - desktop
    - dwm
    - feh
    - firefox
    - git
    - role: gocryptfs
      when: enable_gocryptfs | default('false') | bool
    - hardending
    - iwd
    - role: laptop
      when: "'laptop' in group_names"
    - modprobe
    - mpd
    - mpv
    - neovim
    - newsboat
    - openntpd
    - playerctl
    - rofi
    - ssh
    - sxhkd
    - syncthing
    - tmux
    - unbound
    - xorg
    - zsh
