---
- hosts: desktop
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - apt
    - acpi
    - bluetooth
    - byedpi
    - common
    - chromium
    - console-setup
    - desktop
    - dmenu
    - docker
    - dunst
    - dwm
    - editorconfig
    - feh
    - flameshot
    - role: fwknop
      vars:
        client: true
    - git
    - goimapnotify
    - gpg
    - role: gocryptfs
      when: enable_gocryptfs | default('false') | bool
    - hardending
    - htop
    - interfaces
    - iptables
    - isync
    - iwd
    - role: libvirt
      when: enable_libvirt | default('false') | bool
    - librewolf
    - local_bin
    - modprobe
    - mpd
    - mpv
    - neomutt
    - neovim
    - newsboat
    - openntpd
    - playerctl
    - proxychains
    - rofi
    - slock
    - slstatus
    - spt
    - ssh
    - sxhkd
    - syncthing
    - tmux
    - udev
    - unbound
    - role: v2ray
      when: v2ray_id is defined
    - xorg
    - role: xfce
      when: enable_xfce | default('false') | bool
    - zsh

- hosts: laptop
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - laptop
    - logind
    - tlp
