---
- hosts: desktop
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - apt
    - acpi
    - bluetooth
    - common
    - chromium
    - console-setup
    - desktop
    - dwm
    - dunst
    - editorconfig
    - feh
    - librewolf
    - flameshot
    - git
    - role: gocryptfs
      when: enable_gocryptfs | default('false') | bool
    - gpg
    - hardending
    - iwd
    - role: laptop
      when: "'laptop' in group_names"
    - role: logind
      when: "'laptop' in group_names"
    - role: libvirt
      when: enable_libvirt | default('false') | bool
    - local_bin
    - modprobe
    - mpd
    - mpv
    - neovim
    - newsboat
    - openntpd
    - playerctl
    - podman
    - rofi
    - ssh
    - sxhkd
    - syncthing
    - tmux
    - udev
    - unbound
    - role: xfce
      when: enable_xfce | default('false') | bool
    - xorg
    - zsh
