---
- hosts: all
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - apt
    - acpi
    - bluetooth
    - common
    - console-setup
    - desktop
    - dwm
    - feh
    - git
    - hardending
    - iwd
    - role: laptop
      when: "'laptop' in group_names"
    - modprobe
    - mpv
    - newsboat
    - openntpd
    - playerctl
    - rofi
    - sxhkd
    - tmux
    - unbound
    - xorg
    - zsh
