---
- hosts: '{{ target_host | default("localhost") }}'
  become: true
  become_method: sudo
  gather_facts: true
  connection: local
  vars:
  collections:
    - heldner.things
  roles:
    - iptables


