---
- hosts: laptop
  become: true
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - apt
    - common
    - console-setup
    - dwm
    - feh
    - git
    - hardending
    - laptop
    - modprobe
    - mpv
    - openntpd
    - sxhkd
    - unbound
    - xorg
    - zsh
