---
- hosts: laptop
  become: true
  become_method: sudo
  gather_facts: true
  collections:
    - heldner.things
  roles:
    - apt
    - bluetooth
    - common
    - console-setup
    - dwm
    - feh
    - git
    - hardending
    - laptop
    - modprobe
    - mpv
    - newsboat
    - openntpd
    - playerctl
    - rofi
    - sxhkd
    - unbound
    - xorg
    - zsh
