---
- hosts: mikrotik
  connection: ansible.netcommon.network_cli
  gather_facts: false
  tasks:
    - name: Get info
      community.routeros.command:
        commands: /system/resource/print

    - name: Configure ntp
      community.routeros.command:
        commands:
          - /system/ntp/client/set
            server-dns-names=ru.pool.ntp.org enabled="yes"
      tags: ntp

    - name: Set dhcp server lease time to one hour
      community.routeros.command:
        commands:
          /ip/dhcp-server/set defconf lease-time=01:00:00

    - name: Disable unused services
      community.routeros.command:
        commands:
          - /ip/service/disable "api"
          - /ip/service/disable "api-ssl"
          - /ip/service/disable "telnet"
          - /ip/service/disable "winbox"

    - name: Stop limit wifi power
      community.routeros.command:
        commands:
          /interface/wireless set wlan2 antenna-gain=0
