---
- hosts: rootit
  become_method: sudo
  become: yes
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx_config
      vars:
        nginx_license:
          certificate: ../files/license/nginx-repo.crt
          key: ../files/license/nginx-repo.key
        nginx_remove_license: false
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          app:
            template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              main:
                listen:
                  listen_localhost:
                    port: 80
                server_name: www.rootit.online
                access_log:
                  - name: main
                    location: /var/log/nginx/www.rootit.online.log
                reverse_proxy:
                  locations:
                    main:
                      location: /
                      proxy_pass: http://localhost:8081/
                      proxy_set_header:
                        header_host:
                          name: Host
                          value: $host
              gitea:
                listen:
                  port: 80
                server_name: gitea.rootit.online
                access_log:
                  - name: main
                    location: /var/log/nginx/gitea.rootit.online.log
                reverse_proxy:
                  locations:
                    main:
                      location: /
                      proxy_pass: http://localhost:1313/
                      proxy_set_header:
                        header_host:
                          name: Host
                          value: $host
