---
- hosts: 'all'
  gather_facts: true
  become: false
  collections:
    - heldner.things
  roles:
    - apt
    - common
    - hardending
    - modprobe
    - shadowsocks
    - tmux
    - unbound
    - zsh
