---
- hosts: server
  gather_facts: true
  become: false
  collections:
    - heldner.things
  roles:
    - apt
    - console-setup
    - hardending
    - modprobe
    - nginx
    - shadowsocks
    - ssh
    - tmux
    - unbound
    - v2ray
    - wireguard
    - zsh
