---
- hosts: server
  gather_facts: true
  become: false
  collections:
    - heldner.things
  roles:
    - apt
    - console-setup
    - findmydeviceserver
    - freshrss
    - role: fwknop
      vars:
        server: true
    - hardending
    - iptables
    - modprobe
    - motd
    - neovim
    - nginx
    - noip
    - portsentry
    - radicale
    - ssh
    - tmux
    - unbound
    - v2ray
    - zsh
