---
- hosts: server
  gather_facts: true
  become: false
  collections:
    - heldner.things
  roles:
    - apt
    - console-setup
    - freshrss
    - hardending
    - modprobe
    - motd
    - neovim
    - nginx
    - noip
    - radicale
    - ssh
    - tmux
    - unbound
    - v2ray
    - zsh
