---
- name: Install syncthing
  ansible.builtin.package:
    state: present
    name: syncthing
  tags: syncthing
  become: true

- name: Enable and start syncthing
  ansible.builtin.service:
    name: syncthing
    scope: user
    state: started
    enabled: true
    daemon_reload: true
  tags: syncthing

- name: Iptables allow syncthing connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: '{{ item }}'
    destination_port: 22000
    ctstate: NEW
    jump: ACCEPT
  loop:
    - tcp
    - udp
  notify: Save iptables rules
  become: true
  tags: syncthing
