---
- name: Install syncthing
  ansible.builtin.package:
    state: present
    name: syncthing
  tags: syncthing
  become: true

- name: Enable and start syncthing
  ansible.builtin.service:
    name: syncthing
    scope: user
    state: started
    enabled: true
    daemon_reload: true
