#!/bin/sh

action="$1"
mpclient="/usr/bin/mpc"
notify_icon=/tmp/music_icon.png
track_path="$($mpclient -f '%file%' \
    | awk -F'/' 'NR==1 {for (i=1; i<=(NF-1); i++) printf $i"/"}')"

notify_title() {
  $mpclient | head -1
}

get_music_pic () {
  music_dir="$HOME/Music"
  if ! echo "$track_path" | grep -q 'http:'; then
    music_picture=$(find "${music_dir}/${track_path}" \
      -maxdepth 2 \
      -type f \
      -regextype sed \
      -regex '.*\.\(jpg\|png\|jpeg\)$' \
      -print \
      -quit 2>/dev/null)
  fi

  if [ -n "$music_picture" ]; then
    convert "$music_picture" -scale 256x256 "$notify_icon"
    echo "$notify_icon"
  else
    echo /usr/share/icons/hicolor/scalable/apps/mpd.svg
  fi
}

if [ -n "$action" ]; then
    $mpclient "$action" > /dev/null
fi

[ "$action" = "stop" ] && exit 0

notify-send -u low -i "$(get_music_pic)" "Now playing" "$(notify_title)"
