#!/bin/sh

IFS=$'\n'
VIDEO_HOME="${HOME}/Videos"
MPV_HISTORY="${HOME}/.config/mpv/mpvhistory.log"


dmenu_local () {
    dmenu -c -i \
        -bw 1 \
        -p video \
        -fn '-xos4-terminus-medium-*-*--18-*-*-*-*-*-iso10646-*' \
        -l 20
}

all_videos () {
    pattern='.*(avi|mp4|mkv|webm|m4v|m3u)$'

    find -L "$VIDEO_HOME" \
        -type f \
        -regextype posix-extended \
        -regex "$pattern" \
        -printf "%f\n"
}

history_videos() {
    awk -F'"' '{print $4}' "$MPV_HISTORY" | uniq
}

history_search() {
    awk -v search="$1" -F'"' '$4 ~ search {print $2; exit}' "$MPV_HISTORY"
}

choose_file () {
    (history_videos && all_videos) \
        | sort -h \
        | dmenu_local
}

full_path () {
    file="$1"

    find -L "$VIDEO_HOME" \
        -regextype posix-extended \
        -name "$file" \
        -printf "${VIDEO_HOME}/%P\n"
}

mpd_switch () {
    state="$1"

    if [ "$state" = "paused" ]; then
        mpc -q play
        return
    elif [ "$(mpc | awk 'NR==2 {print $1}')" = "[playing]" ]; then
        mpc -q pause
        echo paused
    fi
}

start_video () {
    file="$1"
    mpd_status=$(mpd_switch)

    mpv "$file" >/dev/null 2>&1
    mpd_switch "$mpd_status"
}

choose_video() {
    file_name="$(choose_file)"
    if [ -n "$file_name" ]; then
        video="$(full_path "$file_name")"
        if [ -z "$video" ]; then
            video="$(history_search "$file_name")"
        fi
        start_video "$video"
    fi
}

if [ -z "$1" ]; then
    choose_video
else
    start_video "$1"
fi
