#!/bin/sh
#
# return totp code from pass
#

pass_find () {
    cd "${HOME}/.password-store" && \
    find . \
        -regextype posix-awk \
        -regex ".*gpg$" \
        -type f \
    | sed -e 's:\.gpg$::' -e 's:\.\/::'
}

key=$(pass_find | dmenu -p otp:)


[ -z "$key" ] && exit 0
if pass otp -c "$key" > /dev/null 2>&1; then
  notify-send -i /usr/share/icons/gnome/32x32/status/dialog-password.png \
    -u low "otp" "$key copied"
fi
