#!/bin/sh
#
# return totp code from pass
#

pass_find () {
    cd "${HOME}/.password-store" && \
    find . \
        -regextype posix-awk \
        -regex ".*gpg$" \
        -type f \
    | sed -e 's:\.gpg$::' -e 's:\.\/::'
}

key=$(pass_find | dmenu -l 20 -p otp:)


if res=$(pass otp -c "$key" 2>&1); then
    notify-send -i emblem-default.png  "OTP" "$key copied"
else
    notify-send -i emblem-important.png "OTP" "$res"
fi

