#!/bin/sh

pass_find () {
    cd "${HOME}/.password-store" && \
    find . \
        -regextype posix-awk \
        -regex ".*gpg$" \
        -type f \
    | sed -e 's:\.gpg$::' -e 's:\.\/::'
}

password=$(pass_find | dmenu -p login:)
[ -z "$password" ] && exit
pass "$password" \
  | awk '/^login:/ {printf $2}' \
  | xclip -selection clipboard
