#!/bin/sh -e


# output from 'xrandr' stdout
[ -z "$OUTPUT" ] && OUTPUT='DP-1'
[ -z "$MODE" ] && MODE='1920x1080'

if [ "$2" = 'hdmi' ]; then
    OUTPUT='HDMI-1'
    MODE='1920x1080'
fi


status () {
    xrandr | grep -q "${OUTPUT}.*${MODE}"
}

off () {
    xrandr --output "$OUTPUT" --off
    exit 0
}

on () {
    xrandr \
        --output "$OUTPUT" \
        --right-of LVDS-1 \
        --mode "$MODE" \
        --gamma 0.8:0.8:0.8
}

toggle () {
    if status; then
        off
    else
        on
    fi
}

usage() {
    echo "Provide command [on|off]"
    exit 1
}

case "$1" in
    status) status;;
    off) off;;
    on) on;;
    *) usage;;
esac
