#!/bin/sh

CMD="$*"
OPTS='-t '

ssh_cmd () {
    if [ -x "$(which rtmux)" ]; then
        echo 'rtmux'
    else
        echo 'ssh'
    fi
}

host=$(awk '$2 !~ /^\*/ && /^Host/ {sub(/\*$/,""); print $2}' ~/.ssh/config \
    | dmenu -p ssh:)

[ -z "$host" ] && exit

if pgrep -lf "$(ssh_cmd).*${host}$"; then
  notify-send "SSH" "Already connected to $host"
else
  urxvtc -e $(ssh_cmd) $OPTS $host "$CMD"
fi

#eval urxvtc -title "ssh $host" -e "$(ssh_cmd)" "$OPTS" "$host" "$CMD"
