#!/bin/sh

PATH=/usr/bin
export DISPLAY=:0.0

wallpaper_dirs="\
${HOME}/Pictures/Wallpapers \
${HOME}/Pictures/Camera
"

[ "$1" = "--cron" ] && sleep "$(date +"%H")m"
# shellcheck disable=SC2086
timeout 5 feh -z --no-fehbg --bg-max $wallpaper_dirs > /dev/null 2>&1
