#!/bin/sh

PATH=/bin:/usr/bin
export DISPLAY=:0.0

wallpaper_dir="${HOME}/Pictures/Wallpapers"

default_bg() {
  timeout 5 feh -z --no-fehbg --bg-max "$wallpaper_dir" > /dev/null 2>&1
}

[ ! -d "$wallpaper_dir" ] && exit 0
[ "$1" = "--cron" ] && sleep "$(date +"%H")m"
default_bg
