#!/bin/sh

DWM="/usr/bin/dwm"

if [ ! -f "$DWM" ]; then
    exit 1
fi

if [ ! -d "${HOME}/.dwm" ]; then
    mkdir "${HOME}/.dwm"
fi

while true; do
    date +"%F %T start dwm"
    $DWM >> ~/.dwm/dwm.log 2>&1
    sleep 1
done
