---
- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for ssh connection
      ansible.builtin.wait_for_connection:
        delay: 2
        timeout: 60
    - ansible.builtin.setup:
      tags: always
  tasks:
    - name: "Include dunst"
      include_role:
        name: "dunst"
