---
- name: Prepare apt
  become: true
  tags: neovim
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version <= "11"
  block:

    - name: Add neovim ppa gpg key
      ansible.builtin.apt_key:
        url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x55f96fcf8231b6dd'
        state: present

    - name: Configure apt
      ansible.builtin.template:
        src: '{{ item.name }}'
        dest: '{{ item.dest }}'
        mode: "0644"
        owner: root
      loop:
        - name: neovim-ppa-ubuntu-stable.list.j2
          dest: /etc/apt/sources.list.d/neovim-ppa-ubuntu-stable.list

    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

- name: Install neovim
  ansible.builtin.package:
    state: present
    name: neovim
  become: true
  tags: neovim

- name: Create home dir
  ansible.builtin.file:
    state: directory
    path: "{{ neovim_home }}"
    mode: "0755"
  tags: neovim

- name: Create dirs
  ansible.builtin.file:
    state: directory
    path: "{{ neovim_home }}/{{ item }}"
    mode: "0755"
  loop:
    - autoload
    - plugged
  tags: neovim

- name: Copy init.vim rc
  ansible.builtin.template:
    src: init.vim.j2
    dest: "{{ neovim_home }}/init.vim"
    mode: "0644"
  notify: Install plugins
  tags: neovim

- name: Fetch plug.vim
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_home }}/autoload/plug.vim"
    creates: "{{ neovim_home }}/autoload/plug.vim"
  tags: neovim

- name: Install python support
  ansible.builtin.package:
    name: python3-pynvim
  become: true
  tags: neovim
