---
- block:

    - name: Add neovim ppa gpg key
      ansible.builtin.apt_key:
        url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x55f96fcf8231b6dd'
        state: present

    - name: Configure apt
      ansible.builtin.template:
        src: '{{ item.name }}'
        dest: '{{ item.dest }}'
        mode: 0644
        owner: root
      loop:
        - name: neovim-ppa-ubuntu-stable.list.j2
          dest: /etc/apt/sources.list.d/neovim-ppa-ubuntu-stable.list

    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

  become: true
  when: ansible_distribution == "Debian"

- name: Install neovim
  ansible.builtin.package:
    state: present
    name: neovim
  become: true

- name: Create home dir
  ansible.builtin.file:
    state: directory
    path: "{{ neovim_home }}"

- name: Create dirs
  ansible.builtin.file:
    state: directory
    path: "{{ neovim_home }}/{{ item }}"
  loop:
    - autoload
    - colors
    - plugged

- name: Copy init.vim rc
  ansible.builtin.template:
    src: init.vim.j2
    dest: "{{ neovim_home }}/init.vim"
  register: _init_vim

- name: Fetch plug.vim
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_home }}/autoload/plug.vim"
    creates: "{{ neovim_home }}/autoload/plug.vim"

- name: Install plugins
  ansible.builtin.shell:
    cmd: nvim -c 'PlugInstall' -c quit -c quit
  when: _init_vim.changed

- name: Create jelybeans link
  ansible.builtin.file:
    state: link
    dest: "{{ neovim_home }}/colors/jellybeans.vim"
    src: "{{ neovim_home }}/plugged/jellybeans.vim/colors/jellybeans.vim"

- name: Install python support
  ansible.builtin.pip:
    name: pynvim
  become: true
