---
- name: Copy hostname config
  ansible.builtin.template:
    src: hostname.wg0.j2
    dest: /etc/hostname.wg0
    mode: "0640"
  become: true
  when: ansible_distribution == "OpenBSD"

- name: Copy wg config
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: "0600"
  register: _wg_config
  become: true

- name: Load wireguard conf
  ansible.builtin.command:
    cmd: /usr/local/bin/wg syncconf wg0 /etc/wireguard/wg0.conf
  when:
    - _wg_config.changed
    - ansible_distribution == "OpenBSD"
  become: true
