---
- name: install pkg
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  become: true

- name: create directory
  ansible.builtin.file:
    dest: /etc/wireguard
    state: directory
    mode: "0700"
  become: true
