---
#- name: install pkg
#  openbsd_pkg:
#    name: "{{ item }}"
#    state: present
#  loop: "{{ packages }}"
#  when: ansible_distribution == "OpenBSD"

- name: install pkg
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  when: ansible_distribution == "Debian"
  become: true

- name: create directory
  file:
    dest: /etc/wireguard
    state: directory
    mode: 0700
  become: true
