---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}/main.yml"
  tags:
    - install

- import_tasks: install.yml
  tags:
    - install

- import_tasks: "configure.yml"
  tags:
    - configure
