---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart dbus
  service:
    name: nginx
    state: restarted
    enabled: true
  when:
    - nginx_app_protect_start | bool
    - not ansible_check_mode | bool
  listen: (Handler - NGINX App Protect) Run NGINX
